### ISSUE TITLE
Fresh install: pnpm build results in error

### ISSUE THREAD

**Issue by jjaimealeman** [zynth17/vitailse#4]
Brand new fresh install.

I go to https://github.com/zynth17/vitailse and click "Use this Template" 
![](https://i.imgur.com/MoZuLGq.png)
And create a new repo from this template.

Git clone my new repo to local.

Run `pnpm i`.

Run `pnpm dev`, works fine! 👍

Run `pnpm build`, results in error. First appears fine: 
![](https://i.imgur.com/7MF10kK.png)

But finishes with error 
![](https://i.imgur.com/qb7ThUl.png)

**Comment by zynth17** [comment]
> Brand new fresh install.
> 
> I go to https://github.com/zynth17/vitailse and click "Use this Template" ![](https://camo.githubusercontent.com/41fb3d4d0c658b19e41c94a10f2dcff5f4daacd206f7a351ef7b331c9396fe27/68747470733a2f2f692e696d6775722e636f6d2f4d6f5a754c47712e706e67) And create a new repo from this template.
> 
> Git clone my new repo to local.
> 
> Run `pnpm i`.
> 
> Run `pnpm dev`, works fine! 👍
> 
> Run `pnpm build`, results in error. First appears fine: ![](https://camo.githubusercontent.com/874b0940213ee6350f7f7414bb32436fc9901f7369ae5df0c1f60f818febd10b/68747470733a2f2f692e696d6775722e636f6d2f374d4631306b4b2e706e67)
> 
> But finishes with error ![](https://camo.githubusercontent.com/8c23322cd3a109d827a66b23d75b35bf8b9a538697d94ae3d0ca44360497447e/68747470733a2f2f692e696d6775722e636f6d2f7162375468556c2e706e67)

you can try to install workbox

**Comment by jjaimealeman** [comment]
> you can try to install workbox

Perhaps it should be included with `pnpm i`?

---

So I installed `workbox`. ![workbox](https://i.imgur.com/DXDY1Td.png)

But it persists with the same error ![workboxerror](https://i.imgur.com/llBiMwS.png)

**Comment by jjaimealeman** [comment]
Also tried `pnpm i workbox-window`, same error results.
