### ISSUE TITLE
How to sort TailwindCSS class without prettier?

### ISSUE THREAD

**Issue by azzamsa** [zynth17/vitailse#79]
Hi.

I see the upstream version opt-out the Prettier. The same thing with this project.
How do you sort TailwindCSS class without [prettier-plugin-tailwindcss](https://github.com/tailwindlabs/prettier-plugin-tailwindcss)?

Thanks.

**Comment by zynth17** [comment]
> Hi.
> 
> I see the upstream version opt-out the Prettier. The same thing with this project. How do you sort TailwindCSS class without [prettier-plugin-tailwindcss](https://github.com/tailwindlabs/prettier-plugin-tailwindcss)?
> 
> Thanks.

use this vscode ext https://marketplace.visualstudio.com/items?itemName=heybourn.headwind

**Comment by azzamsa** [comment]
> > Hi.
> > I see the upstream version opt-out the Prettier. The same thing with this project. How do you sort TailwindCSS class without [prettier-plugin-tailwindcss](https://github.com/tailwindlabs/prettier-plugin-tailwindcss)?
> > Thanks.
> 
> use this vscode ext https://marketplace.visualstudio.com/items?itemName=heybourn.headwind

Oh, Unfortunately, I don't use VsCode. CLI app is preferred. I will keep using Prettier, then.

**Comment by azzamsa** [comment]
If anyone looking for CLI solution to format TailwindCSS class, use [avencera/rustywind: CLI for organizing Tailwind CSS classes](https://github.com/avencera/rustywind)
