### ISSUE TITLE
pnpm build gives syntax error vite-ssg

### ISSUE THREAD

**Issue by Warhead5555** [zynth17/vitailse#8]
I can't seem to build this template after fresh initial install. 

First `pnpm i`

Then ` pnpm dev `
Running the dev server works fine.

`pnpm build`
Trying to build the project results in the following error:
![image](https://user-images.githubusercontent.com/4640259/162685363-5a4a34f2-cd9a-454c-8ddf-c12915f9c222.png)

**Comment by zynth17** [comment]
> I can't seem to build this template after fresh initial install.
> 
> First `pnpm i`
> 
> Then `pnpm dev` Running the dev server works fine.
> 
> `pnpm build` Trying to build the project results in the following error: ![image](https://user-images.githubusercontent.com/4640259/162685363-5a4a34f2-cd9a-454c-8ddf-c12915f9c222.png)

should fix with the latest commit. let me know if it still does not work.
