### ISSUE TITLE
"Process is not defined" error in browser

### ISSUE THREAD

**Issue by Hellrasier** [zynth17/vitailse#96]
When started application with `pnpm dev` no logs were on server side. After connecting to the url with browser got an error
![image](https://user-images.githubusercontent.com/65816075/186025212-10facd9e-eba2-4de5-bf7c-34b55836f808.png)

**Comment by hay-kot** [comment]
Related to 

- https://github.com/vitejs/vite/issues/1973

Replacing `process.env` with `import.meta.env` seems to resolve the issue

**Comment by zynth17** [comment]
process is a server side thing .
if in browser use `import.meta.env` like stated in vite documentation.
thankyou @hay-kot for answering.
